"""
MileWatch — Delivery Attempt Data Generator

WHY THIS APPROACH:
We sample from behavioral profiles, NOT random distributions.
Each row is generated by first picking a profile (archetype), then sampling
all features from that profile's correlated distributions.

This ensures the model learns real patterns:
- "Far GPS + no call + short time gap + COD" = likely fake
- "Close GPS + call made + normal timing" = likely genuine

USAGE:
    python generator.py                    # Default: 15000 samples
    python generator.py --samples 50000   # Custom sample count
    python generator.py --seed 42          # Reproducible output
"""

import argparse
import uuid
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from profiles import (
    ALL_PROFILES,
    FEATURE_COLUMNS,
    BehavioralProfile,
    FeatureDistribution,
)


def sample_feature(dist: FeatureDistribution, rng: np.random.Generator, size: int) -> np.ndarray:
    """
    Sample `size` values from a feature distribution.

    Handles clamping for normal distributions to respect min/max bounds,
    and weighted categorical sampling.
    """
    if dist.dist_type == "normal":
        values = rng.normal(
            loc=dist.params["mean"],
            scale=dist.params["std"],
            size=size
        )
        return np.clip(values, dist.params["min"], dist.params["max"])

    elif dist.dist_type == "uniform":
        return rng.uniform(
            low=dist.params["low"],
            high=dist.params["high"],
            size=size
        )

    elif dist.dist_type == "binary":
        return rng.binomial(n=1, p=dist.params["probability"], size=size)

    elif dist.dist_type == "categorical":
        categories = list(dist.params["weights"].keys())
        probabilities = list(dist.params["weights"].values())
        return rng.choice(categories, size=size, p=probabilities)

    else:
        raise ValueError(f"Unknown distribution type: {dist.dist_type}")


def compute_credibility_score(
    row: dict,
    profile: BehavioralProfile,
    rng: np.random.Generator,
) -> float:
    """
    Compute the credibility score for a single row based on profile weights.

    WHY NOT JUST RANDOM:
    The score is a weighted combination of normalized feature values.
    This means the model can't simply reverse-engineer a formula — it has to
    learn the relationship between features and credibility. Gaussian noise
    prevents perfect memorization.

    Feature normalization:
    - Each feature is normalized to [0, 1] where 1 = most credible signal.
    - For GPS distance: closer = more credible → inverse normalization.
    - For call_made: 1 = credible (called).
    - For time_gap: moderate time (25-45 min) = most credible.
    - For is_cod: prepaid = slightly more credible (less motive to fake).
    - For fake_rate: lower = more credible → inverse normalization.
    - For shift_end: more time remaining = more credible.
    - For pincode_tier: metro = slightly more credible (better tracking).
    """
    weights = profile.score_weights

    # Normalize each feature to [0, 1] credibility contribution
    # GPS: 0m = 1.0 (perfect), 5000m+ = 0.0 (very suspicious)
    gps_norm = max(0.0, 1.0 - (row["gps_distance_m"] / 5000.0))

    # Time gap: 25-45 min is ideal. Too short or too long is suspicious.
    ideal_time = 35.0
    time_dev = abs(row["time_gap_minutes"] - ideal_time)
    time_norm = max(0.0, 1.0 - (time_dev / 60.0))

    # Call made: binary, 1 = good
    call_norm = float(row["call_made"])

    # COD: prepaid = 1.0 (less motive), COD = 0.6 (some motive to skip)
    cod_norm = 0.6 if row["is_cod"] == 1 else 1.0

    # Historical fake rate: 0% = 1.0, 50% = 0.0
    fake_norm = max(0.0, 1.0 - (row["exec_historical_fake_rate"] / 0.50))

    # Shift end: 480 min remaining = 1.0, 0 min = 0.0
    shift_norm = min(1.0, row["minutes_to_shift_end"] / 480.0)

    # Pincode tier: 1 (metro) = 1.0, 2 = 0.7, 3 = 0.5
    tier_map = {1: 1.0, 2: 0.7, 3: 0.5}
    tier_norm = tier_map.get(int(row["pincode_tier"]), 0.5)

    # Weighted sum
    raw_score = (
        weights["gps_distance_m"] * gps_norm
        + weights["call_made"] * call_norm
        + weights["time_gap_minutes"] * time_norm
        + weights["is_cod"] * cod_norm
        + weights["exec_historical_fake_rate"] * fake_norm
        + weights["minutes_to_shift_end"] * shift_norm
        + weights["pincode_tier"] * tier_norm
    )

    # Add Gaussian noise to prevent perfect formula reversal
    noise = rng.normal(loc=0.0, scale=0.05)
    raw_score += noise

    # Clamp to the profile's credibility range
    cred_min, cred_max = profile.credibility_range
    return float(np.clip(raw_score, cred_min, cred_max))


def generate_profile_data(
    profile: BehavioralProfile,
    count: int,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """Generate `count` delivery attempt records from a single behavioral profile."""

    data = {}

    # Sample each feature from the profile's distribution
    for feature_name in FEATURE_COLUMNS:
        dist: FeatureDistribution = getattr(profile, feature_name)
        data[feature_name] = sample_feature(dist, rng, count)

    df = pd.DataFrame(data)

    # Generate attempt IDs
    df["attempt_id"] = [str(uuid.uuid4()) for _ in range(count)]

    # Tag the profile (for analysis only — NOT a model feature)
    df["profile"] = profile.name

    # Compute credibility scores
    df["credibility_score"] = df.apply(
        lambda row: compute_credibility_score(row.to_dict(), profile, rng),
        axis=1,
    )

    return df


def generate_dataset(total_samples: int, seed: int = 42) -> pd.DataFrame:
    """
    Generate the full delivery attempt dataset from all behavioral profiles.

    Samples are allocated proportionally across profiles, then shuffled.
    """
    rng = np.random.default_rng(seed)
    frames = []

    for profile in ALL_PROFILES:
        count = int(total_samples * profile.proportion)
        if count == 0:
            continue

        print(f"  Generating {count:>6,} samples for {profile.name}...")
        df = generate_profile_data(profile, count, rng)
        frames.append(df)

    # Combine and shuffle
    dataset = pd.concat(frames, ignore_index=True)
    dataset = dataset.sample(frac=1.0, random_state=seed).reset_index(drop=True)

    # Enforce dtypes
    dataset["call_made"] = dataset["call_made"].astype(int)
    dataset["is_cod"] = dataset["is_cod"].astype(int)
    dataset["pincode_tier"] = dataset["pincode_tier"].astype(int)
    dataset["gps_distance_m"] = dataset["gps_distance_m"].round(1)
    dataset["time_gap_minutes"] = dataset["time_gap_minutes"].round(1)
    dataset["exec_historical_fake_rate"] = dataset["exec_historical_fake_rate"].round(4)
    dataset["minutes_to_shift_end"] = dataset["minutes_to_shift_end"].round(1)
    dataset["credibility_score"] = dataset["credibility_score"].round(4)

    # Reorder columns
    column_order = [
        "attempt_id",
        *FEATURE_COLUMNS,
        "credibility_score",
        "profile",
    ]
    dataset = dataset[column_order]

    return dataset


def print_summary(df: pd.DataFrame) -> None:
    """Print a summary of the generated dataset for quick validation."""
    print("\n" + "=" * 70)
    print("DATASET SUMMARY")
    print("=" * 70)

    print(f"\nTotal records: {len(df):,}")
    print(f"\nProfile distribution:")
    profile_counts = df["profile"].value_counts()
    for profile_name, count in profile_counts.items():
        pct = count / len(df) * 100
        print(f"  {profile_name:<25} {count:>6,}  ({pct:5.1f}%)")

    print(f"\nCredibility score stats:")
    print(f"  Mean:   {df['credibility_score'].mean():.4f}")
    print(f"  Std:    {df['credibility_score'].std():.4f}")
    print(f"  Min:    {df['credibility_score'].min():.4f}")
    print(f"  Max:    {df['credibility_score'].max():.4f}")

    print(f"\nFeature stats:")
    for col in FEATURE_COLUMNS:
        print(f"  {col:<30} mean={df[col].mean():>10.2f}  std={df[col].std():>10.2f}")

    print(f"\nSample rows:")
    print(df.head(5).to_string(index=False))
    print("=" * 70)


def main():
    parser = argparse.ArgumentParser(
        description="Generate synthetic delivery attempt data for MileWatch"
    )
    parser.add_argument(
        "--samples", type=int, default=15000,
        help="Total number of samples to generate (default: 15000)"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for reproducibility (default: 42)"
    )
    parser.add_argument(
        "--output", type=str, default=None,
        help="Output CSV path (default: ./generated/delivery_attempts.csv)"
    )

    args = parser.parse_args()

    # Default output path
    if args.output is None:
        output_dir = Path(__file__).parent / "generated"
        output_dir.mkdir(exist_ok=True)
        output_path = output_dir / "delivery_attempts.csv"
    else:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"MileWatch Data Generator")
    print(f"  Samples:  {args.samples:,}")
    print(f"  Seed:     {args.seed}")
    print(f"  Output:   {output_path}")
    print()

    # Generate
    df = generate_dataset(total_samples=args.samples, seed=args.seed)

    # Save
    df.to_csv(output_path, index=False)
    print(f"\nSaved to: {output_path}")

    # Summary
    print_summary(df)

    return 0


if __name__ == "__main__":
    sys.exit(main())
