"""
MileWatch — Auto Dispute Draft Generator

WHY THIS FILE EXISTS:
When a delivery attempt is flagged as suspicious, ops managers need to file
a formal dispute with the logistics partner. Writing these from scratch is
tedious and inconsistent. This module auto-generates professional dispute
drafts based on the credibility score and SHAP-based reasons.

HOW IT WORKS:
1. Takes a credibility score, risk level, and list of Reason objects
2. Selects a template based on risk level (HIGH_RISK gets strongest language)
3. Fills dynamic slots with specific data from the reasons
4. Returns a ready-to-send dispute paragraph

DESIGN DECISION: Template-based (not LLM-generated) because:
- Deterministic output — same input = same draft every time
- No external API dependency
- Ops managers want consistent, professional language, not creative writing
- Templates can be legally reviewed once and reused
"""

from typing import List
from datetime import datetime

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "model"))
from explainer import Reason


# ── Risk level labels ──────────────────────────────────────────────────

RISK_LABELS = {
    "HIGH_RISK": "LOW CREDIBILITY",
    "MEDIUM_RISK": "MEDIUM CREDIBILITY",
    "LOW_RISK": "HIGH CREDIBILITY",
}

RISK_ACTIONS = {
    "HIGH_RISK": "We strongly recommend this attempt be flagged for immediate review and investigation.",
    "MEDIUM_RISK": "We recommend this attempt be reviewed for potential irregularities.",
    "LOW_RISK": "This attempt appears genuine based on available signals, but minor concerns were noted.",
}


def _format_reason_bullet(reason: Reason, index: int) -> str:
    """Format a single reason as a numbered bullet point for the dispute draft."""
    direction_icon = "⚠️" if reason.direction == "negative" else "✓"
    return f"  {index}. {direction_icon} {reason.description}"


def _get_negative_reasons(reasons: List[Reason]) -> List[Reason]:
    """Filter to only negative (credibility-reducing) reasons."""
    return [r for r in reasons if r.direction == "negative"]


def generate_dispute_draft(
    score: float,
    risk_level: str,
    reasons: List[Reason],
    attempt_id: str = None,
    date: str = None,
) -> str:
    """
    Generate a human-readable dispute draft based on prediction results.

    Args:
        score: Credibility score (0.0 - 1.0)
        risk_level: One of HIGH_RISK, MEDIUM_RISK, LOW_RISK
        reasons: List of Reason objects from the explainer
        attempt_id: Optional attempt ID for reference
        date: Optional date string, defaults to today

    Returns:
        Formatted dispute draft string ready for review/sending
    """
    if date is None:
        date = datetime.now().strftime("%B %d, %Y")

    if attempt_id is None:
        attempt_id = "N/A"

    credibility_label = RISK_LABELS.get(risk_level, "UNKNOWN")
    action_text = RISK_ACTIONS.get(risk_level, "Please review this attempt.")

    # Get the negative reasons (the ones that actually warrant a dispute)
    negative_reasons = _get_negative_reasons(reasons)

    # If there are negative reasons, build the findings section
    if negative_reasons:
        findings_bullets = "\n".join(
            _format_reason_bullet(r, i)
            for i, r in enumerate(negative_reasons, 1)
        )
        findings_section = f"\nKey findings:\n{findings_bullets}\n"
    else:
        findings_section = "\nNo specific risk indicators were identified.\n"

    # Build the draft based on risk level
    if risk_level == "HIGH_RISK":
        draft = (
            f"DELIVERY ATTEMPT DISPUTE — {credibility_label}\n"
            f"{'=' * 50}\n\n"
            f"Date: {date}\n"
            f"Attempt Reference: {attempt_id}\n\n"
            f"This delivery attempt has been analyzed by MileWatch's credibility "
            f"scoring system and received a score of {score:.2f} out of 1.00, "
            f"indicating {credibility_label}.\n"
            f"{findings_section}\n"
            f"Based on the combination of these factors, there is strong evidence "
            f"suggesting this delivery attempt may not have been genuinely attempted. "
            f"{action_text}\n\n"
            f"This analysis is based on automated pattern detection comparing this "
            f"attempt against historical delivery data. Human review is recommended "
            f"before taking final action.\n\n"
            f"— Generated by MileWatch Credibility Scoring System"
        )

    elif risk_level == "MEDIUM_RISK":
        draft = (
            f"DELIVERY ATTEMPT REVIEW — {credibility_label}\n"
            f"{'=' * 50}\n\n"
            f"Date: {date}\n"
            f"Attempt Reference: {attempt_id}\n\n"
            f"This delivery attempt has been analyzed by MileWatch's credibility "
            f"scoring system and received a score of {score:.2f} out of 1.00, "
            f"indicating {credibility_label}. While not conclusively suspicious, "
            f"some patterns warrant a closer look.\n"
            f"{findings_section}\n"
            f"{action_text} This attempt falls in a borderline range where "
            f"additional context from the delivery executive may clarify the situation.\n\n"
            f"— Generated by MileWatch Credibility Scoring System"
        )

    else:  # LOW_RISK
        draft = (
            f"DELIVERY ATTEMPT ASSESSMENT — {credibility_label}\n"
            f"{'=' * 50}\n\n"
            f"Date: {date}\n"
            f"Attempt Reference: {attempt_id}\n\n"
            f"This delivery attempt has been analyzed by MileWatch's credibility "
            f"scoring system and received a score of {score:.2f} out of 1.00, "
            f"indicating {credibility_label}.\n"
            f"{findings_section}\n"
            f"{action_text}\n\n"
            f"— Generated by MileWatch Credibility Scoring System"
        )

    return draft
